baseURL = "https://uiyx.xyz/"
languageCode = "en-us"
title = "Obsolete Flesh"
theme="uiX"
# Code Highlight
pygmentsstyle = "dracula"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "flesh-1"

paginate=3 # articles per page

favicon = "https://uiyx.xyz/img/favicon.png" 

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Still needed for machine reproduction."
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

# Social Tags

[[params.social]]
name = "X/Twitter"
icon = "twitter"
url = "https://twitter.com/bodilyflesh/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/coldcatallactics"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

